heat_template_version: 2015-10-15

description: |
  #### Production - RCv3
  This stack is intended for low to medium traffic production
  websites and can be scaled as needed to accommodate future
  growth.  This stack includes a Cloud Load Balancer, Cloud
  Database, and a Master server (plus optional secondary
  servers).  It also includes Cloud Monitoring and Cloud
  Backups.

  This stack is running the latest version of
  [nginx](https://www.nginx.com/),
  and [PHP FPM](http://php-fpm.org/).
  with a Cloud Database running
  [MySQL 5.6](http://www.mysql.com/about/).

  This template will only function with RackConnect v3.
parameter_groups:
- label: PHP Settings
  parameters:
  - php_url
  - db_user
  - db_name
  - php_myadmin
- label: RackConnect Settings
  parameters:
  - rc_network_name
- label: rax-dev-params
  parameters:
  - server_image
  - secondary_template
  - ansible_branch
  - ansible_repo

parameters:
  #PHP Customization
  php_url:
    type: string
    default: example.com
    label: Site Domain
    description: Domain used to configure Nginx
    constraints:
    - allowed_pattern: "^[a-zA-Z0-9.-]{1,255}.[a-zA-Z]{2,15}$"
      description: Must be a valid domain name
    immutable: true
  db_user:
    type: string
    default: example
    label: Database User
    description: Username to configure for SQL
    constraints:
    - allowed_pattern: "^[a-zA-Z0-9.-]{1,255}$"
      description: Must only contain alphanumeric characters, '-', and '.'
    immutable: true
  db_name:
    type: string
    default: example
    label: Database Name
    description: Database to configure in SQL
    constraints:
    - allowed_pattern: "^[a-zA-Z0-9.-]{1,255}$"
      description: Must only contain alphanumeric characters, '-', and '.'
    immutable: true
  php_myadmin:
    type: boolean
    default: false
    label: PHPMyAdmin
    description: Enable or disable PHPMyAdmin
    immutable: true
  backup_email:
    type: string
    default: admin@example.com
    label: E-mail
    description: E-mail address to be notified for failing backups
    immutable: true
  rc_network_name:
    type: string
    label: RackConnect Network
    description: Name or UUID of RackConnected network to attach this server to
    constraints:
    - custom_constraint: rackconnect.network
    immutable: true
  #Advanced Options
  lsync_directory:
    type: string
    default: "/var/www"
    label: Shared Directory
    description: This directory will be synchronized between all servers within this stack.  Leave blank to manually configure Lsyncd
  server_flavor:
    type: string
    default: 4 GB General Purpose v1
    label: Server Flavor
    description: Flavor of Cloud Server to be used for all servers in this stack
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
    immutable: true
  database_disk:
    type: number
    default: 5
    constraints:
    - range:
        min: 5
        max: 500
    label: Database Disk (in GB)
    description: Size of the Cloud Database volume in GB
  database_flavor:
    type: string
    default: 1GB Instance
    label: Cloud Database Flavor
    description: Flavor for the Cloud Database
    constraints:
    - allowed_values:
      - 1GB Instance
      - 2GB Instance
      - 4GB Instance
      - 8GB Instance
      - 16GB Instance
      - 32GB Instance
      - 64GB Instance
  server_image:
    type: string
    default: f4bbbce2-50b0-4b07-bf09-96c175a45f4b
    label: Server Image
    description: Image to be used for all servers in this stack
    constraints:
    - allowed_values:
      - f4bbbce2-50b0-4b07-bf09-96c175a45f4b
    immutable: true
  server_count:
    type: number
    default: 0
    label: Number of Secondary Servers
    description: Number of secondary web nodes
    constraints:
      - range: { min: 0, max: 10 }
  loadbalancer_flavor:
    type: string
    default: 2 GB General Purpose v1
    label: Server Flavor
    description: Flavor of Cloud Server to use for the load balancer
    constraints:
    - allowed_values:
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
    immutable: true
  secondary_template:
    type: string
    default: https://raw.githubusercontent.com/rackspace-orchestration-templates/php-small-rc/stable/php-small-rc-secondary.yaml
    label: Secondary Template
    description: Template to use for secondary servers
    immutable: true
  ansible_branch:
    type: string
    default: stable
    label: Git Branch or Tag for Ansible Roles
    description: The Ansible Roles will be pulled from Git, using the tag or branch provided
    immutable: true
  ansible_repo:
    type: string
    default: https://github.com/rackspace-orchestration-templates/ansible-roles.git
    label: Git Repo for Ansible Roles
    description: The Ansible Roles will be pulled from Git, using the repo provided
    immutable: true

resources:
  #Passwords
  database_pass:
    type: OS::Heat::RandomString
  holland_pass:
    type: OS::Heat::RandomString
  #SSH Key
  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true
  #Cloud Database
  php_database:
    type: OS::Trove::Instance
    properties:
      name:
        str_replace:
          template: stack_Database
          params:
            stack: { get_param: "OS::stack_name" }
      flavor: { get_param: database_flavor }
      size: { get_param: database_disk }
      datastore_type: mysql
      databases:
      - name: { get_param: db_name }
      - name: phpmyadmin
      users:
      - name: { get_param: db_user }
        password: { get_attr: [database_pass, value] }
        databases: [ { get_param: db_name } , phpmyadmin]
      - name: holland
        password: { get_attr: [holland_pass, value] }
        databases: [ { get_param: db_name } , phpmyadmin]
  #Software Configurations
  upload_role_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      outputs:
      - name: results
      config:
        str_replace:
          template: |
            #!/bin/bash
            set -e
            git clone -b 'tag' --single-branch --progress repository /etc/ansible/roles > $heat_outputs_path.results 2>&1
          params:
            tag: { get_param: ansible_branch}
            repository: { get_param: ansible_repo }

  php_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config: |
        ---
        - name: Install and configure PHP
          hosts: localhost
          connection: local
          roles:
          - common
          - nginx
          - php-fpm
          - holland
          - phpmyadmin
  other_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
      - default: "[]"
        name: lsync_dirs
        type: CommaDelimitedList
      - default: "[]"
        name: lsync_servers
        type: CommaDelimitedList
      - default: "[]"
        name: firewall_nodes
        type: CommaDelimitedList
      - default: "[]"
        name: firewall_node_rules
        type: CommaDelimitedList
      config: |
        ---
        - name: Install and configure other things
          hosts: localhost
          connection: local
          roles:
          - firewall
          - lsync
  deploy_roles:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: upload_role_config
      server:
        get_resource: php_server
  deploy_php:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_roles
    properties:
      signal_transport: TEMP_URL_SIGNAL
      input_values:
        nginx_vhost_str: { get_param: php_url }
        nginx_vhost_template: "default"
        nginx_vhost_phpmyadmin: { get_param: php_myadmin }
        tz: "America/Chicago"
        holland_mysql_user: "holland"
        holland_mysql_password: {  get_attr: [holland_pass, value] }
        holland_mysql_host: { get_attr: [php_database, hostname] }
        holland_create_user: "no"
        phpmyadmin_host: { get_attr: [php_database, hostname] }
        phpmyadmin_user: { get_param: db_user }
        phpmyadmin_pass: { get_attr: [database_pass, value] }
      config:
        get_resource: php_config
      server:
        get_resource: php_server
  other_php:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_roles
    properties:
      signal_transport: TEMP_URL_SIGNAL
      input_values:
        lsync_dirs: [ { get_param: lsync_directory } ]
        lsync_private_key: { get_attr: [ssh_key, private_key] }
        lsync_servers: { get_attr: [php_secondary, public_ip] }
        firewall_global_rules: [ "0.0.0.0,0,22,tcp", "0.0.0.0,0,80,tcp", "0.0.0.0,0,443,tcp"]
        firewall_nodes: { get_attr: [php_secondary, public_ip] }
        firewall_node_rules: []
      config:
        get_resource: other_config
      server:
        get_resource: php_server
  #Master Server
  php_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: "OS::stack_name" }
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      key_name: { get_resource: ssh_key }
      software_config_transport: POLL_TEMP_URL
      config_drive: true
      user_data_format: SOFTWARE_CONFIG
      networks:
      - network: { get_param: rc_network_name }
      - uuid: 11111111-1111-1111-1111-111111111111
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        build_config: "backup_agent_only,monitoring_agent_only"
  php_server_public_ip:
    type: Rackspace::RackConnect::PublicIP
    depends_on:
    - php_server
    properties:
      server_id: { get_resource: php_server }
  #Monitoring Checks
  load_balancer_http_check:
    type: Rackspace::CloudMonitoring::Check
    depends_on: load_balancer_public_ip
    properties:
      entity: { get_resource: load_balancer }
      type: remote.http
      label:
        str_replace:
          template: stack Load Balancer HTTP Check
          params:
            stack: { get_param: "OS::stack_name" }
      details:
        url:
          str_replace:
            template: "http://ipaddr"
            params:
              ipaddr: { get_attr: [load_balancer, accessIPv4] }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
      period: 120
      timeout: 10
      monitoring_zones_poll:
      - Northern Virginia (IAD)
      - Chicago (ORD)
      - Dallas Fort Worth (DFW)
      - London (LON)
      target_hostname: { get_attr: [load_balancer, accessIPv4] }
      target_receiver: IPv4
  #Cloud Backup
  php_backup:
    type: Rackspace::Cloud::BackupConfig
    depends_on: php_server
    properties:
      host_ip_address: { get_attr: [php_server, networks, private, 0] }
      BackupConfigurationName:
        str_replace:
          template: stack Weekly Backup
          params:
            stack: { get_param: "OS::stack_name" }
      Inclusions:
      - FilePath: "/var/spool/holland"
        FileItemType: "Folder"
      - FilePath: "/var/www"
        FileItemType: "Folder"
      NotifyFailure: true
      NotifyRecipients: { get_param: backup_email }
      TimeZoneId: Central Standard Time
      StartTimeAmPm: AM
      StartTimeHour: 1
      StartTimeMinute: 0
      HourInterval: null
      DayOfWeekId: 0
      Frequency: "Weekly"
      VersionRetention: 30
  #Secondary Server
  php_secondary:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: server_count }
      resource_def:
        type: { get_param: secondary_template }
        properties:
          ssh_key: { get_resource: ssh_key }
          parent_stack_id: { get_param: "OS::stack_id" }
          server_image: { get_param: server_image }
          server_flavor: { get_param: server_flavor }
          apache_default_domain: { get_param: php_url }
          php_myadmin: { get_param: php_myadmin }
          server_name:
            str_replace:
              template: stack-secondary-%index%
              params:
                stack: { get_param: "OS::stack_name" }
          master_server: { get_attr: [php_server, networks, { get_param: rc_network_name }, 0] }
          rc_network_name: { get_param: rc_network_name }
          ansible_branch: { get_param: ansible_branch}
          ansible_repo: { get_param: ansible_repo }
  #nginx load balancer
  upload_lb_role_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      outputs:
      - name: results
      config:
        str_replace:
          template: |
            #!/bin/bash
            set -e
            git clone -b 'tag' --single-branch --progress repository /etc/ansible/roles > $heat_outputs_path.results 2>&1
          params:
            tag: { get_param: ansible_branch}
            repository: { get_param: ansible_repo }
  deploy_lb_roles:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: upload_lb_role_config
      server:
        get_resource: load_balancer
  deploy_loadbalancer:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_lb_roles
    properties:
      signal_transport: TEMP_URL_SIGNAL
      input_values:
        nginx_vhost_str: { get_param: php_url }
        nginx_vhost_template: "loadbalancer"
        nginx_upstream_server: { get_attr: [php_server, networks, { get_param: rc_network_name}, 0] }
        nginx_lb_nodes: { get_attr: [php_secondary, public_ip] }
        firewall_global_rules: [ "0.0.0.0,0,22,tcp", "0.0.0.0,0,80,tcp", "0.0.0.0,0,443,tcp"]
      config:
        get_resource: loadbalancer_config
      server:
        get_resource: load_balancer
  loadbalancer_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
      - default: "[]"
        name: nginx_lb_nodes
        type: CommaDelimitedList
      - default: "[]"
        name: firewall_global_rules
        type: CommaDelimitedList
      config: |
        ---
        - name: Install and configure nginx as Load Balancer
          hosts: localhost
          connection: local
          roles:
          - nginx
          - firewall
  load_balancer:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: stack_Load_Balancer
          params:
            stack: { get_param: "OS::stack_name" }
      image: { get_param: server_image }
      flavor: { get_param: loadbalancer_flavor }
      key_name: { get_resource: ssh_key }
      software_config_transport: POLL_TEMP_URL
      config_drive: true
      user_data_format: SOFTWARE_CONFIG
      networks:
      - network: { get_param: rc_network_name }
      - uuid: 11111111-1111-1111-1111-111111111111
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        build_config: "monitoring_agent_only"
  load_balancer_public_ip:
    type: Rackspace::RackConnect::PublicIP
    depends_on:
    - load_balancer
    properties:
      server_id: { get_resource: load_balancer }

outputs:
  php_public_ip:
    description: Load Balancer IP
    value:
      get_attr: [load_balancer, accessIPv4]
  php_public_url:
    description: Public URL
    value:
      str_replace:
        template: "http://domain/"
        params:
          domain: { get_param: php_url }
  phpmyadmin_url:
    description: PHPMyAdmin URL (if enabled)
    value:
      str_replace:
        template: "https://IP/phpmyadmin/"
        params:
          IP:
            get_attr: [load_balancer, accessIPv4]
  mysql_user:
    description: Database User
    value: { get_param: db_user }
  mysql_database:
    description: Database Name
    value: {get_param: db_name }
  mysql_password:
    description: Database Password
    value:
      get_attr: [database_pass, value]
  mysql_host:
    description: Database Host
    value:
      get_attr: [php_database, hostname]
  ssh_private_key:
    description: SSH Private Key
    value:
      get_attr: [ssh_key, private_key]
  server_ip:
    description: Server Public IP
    value:
      get_attr: [php_server, accessIPv4]
  secondary_ips:
    description: Secondary Node IPs
    value:
      get_attr: [php_secondary, public_ip]
